"""
PDF Report Generator
Exports a complete emotional wellness report using ReportLab.
"""
import io
import json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

PAGE_W, PAGE_H = A4
MARGIN = 2 * cm

BLACK  = colors.HexColor("#0a0a0a")
GRAY   = colors.HexColor("#555555")
LGRAY  = colors.HexColor("#cccccc")
WHITE  = colors.white
ACCENT = colors.HexColor("#6366f1")


def _styles():
    ss = getSampleStyleSheet()
    title = ParagraphStyle(
        "ReportTitle",
        parent=ss["Title"],
        fontSize=24, textColor=BLACK, leading=30, spaceAfter=4
    )
    subtitle = ParagraphStyle(
        "Subtitle",
        parent=ss["Normal"],
        fontSize=10, textColor=GRAY, spaceAfter=20
    )
    section = ParagraphStyle(
        "Section",
        parent=ss["Heading2"],
        fontSize=13, textColor=BLACK, spaceBefore=16, spaceAfter=6,
        borderPad=2
    )
    body = ParagraphStyle(
        "Body",
        parent=ss["Normal"],
        fontSize=9, textColor=GRAY, leading=14, spaceAfter=4
    )
    insight = ParagraphStyle(
        "Insight",
        parent=ss["Normal"],
        fontSize=10, textColor=BLACK, leading=16,
        backColor=colors.HexColor("#f5f5f5"), borderPad=8, spaceAfter=10
    )
    return title, subtitle, section, body, insight


def generate_pdf(session_id: str, checkins: list[dict], trend: dict | None) -> bytes:
    """Build and return PDF bytes for the emotional wellness report."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=MARGIN
    )

    title_style, subtitle_style, section_style, body_style, insight_style = _styles()
    story = []

    # ── Header ──────────────────────────────────────────────────────────────
    story.append(Paragraph("MindTrack", title_style))
    story.append(Paragraph("Emotional Wellness Report", subtitle_style))
    story.append(Paragraph(
        f"Generated: {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')} | "
        f"Session: {session_id[:8]}…",
        body_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=LGRAY, spaceAfter=16))

    # Disclaimer
    story.append(Paragraph(
        "⚠️  DISCLAIMER: This report is generated by an AI wellness tool and is NOT a medical diagnosis. "
        "Please consult a qualified mental health professional for clinical assessment and treatment.",
        insight_style
    ))

    # ── Summary ───────────────────────────────────────────────────────────────
    if trend:
        story.append(Paragraph("Summary Statistics", section_style))
        days = trend.get("days_tracked", len(checkins))
        summary_data = [
            ["Metric", "Value"],
            ["Days Tracked", str(days)],
            ["Avg. Emotional State", f"{trend.get('avg_emotional_state') or 'N/A'}"],
            ["Avg. Stress Level",    f"{trend.get('avg_stress') or 'N/A'}"],
            ["Avg. Motivation",      f"{trend.get('avg_motivation') or 'N/A'}"],
            ["Avg. Sentiment Score", f"{trend.get('avg_sentiment') or 'N/A'}"],
            ["Variability Score",    f"{trend.get('variability_score') or 'N/A'}"],
            ["Trend Direction",      (trend.get("trend_direction") or "stable").upper()],
            ["Mood Swings Detected", "YES" if trend.get("mood_swing_detected") else "NO"],
            ["Stress Spike Detected","YES" if trend.get("stress_spike_detected") else "NO"],
        ]
        t = Table(summary_data, colWidths=[8 * cm, 8 * cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, 0), BLACK),
            ("TEXTCOLOR",    (0, 0), (-1, 0), WHITE),
            ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.HexColor("#f9f9f9"), WHITE]),
            ("GRID",         (0, 0), (-1, -1), 0.5, LGRAY),
            ("LEFTPADDING",  (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING",   (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 12))

        # Insights
        if trend.get("insight_message"):
            story.append(Paragraph("AI Insights", section_style))
            for part in trend["insight_message"].split(" | "):
                story.append(Paragraph(part.strip(), insight_style))

    # ── Daily Log ─────────────────────────────────────────────────────────────
    if checkins:
        story.append(Paragraph("Daily Check-in Log", section_style))
        headers = ["Date", "Mood", "Stress", "Cognition", "Motivation", "Sentiment", "Emotion", "CBT Category"]
        rows = [headers]
        for c in checkins:
            kw = ""
            if c.get("keywords"):
                try:
                    kw_list = json.loads(c["keywords"])
                    kw = ", ".join(kw_list[:4])
                except Exception:
                    kw = str(c.get("keywords", ""))
            rows.append([
                str(c.get("checkin_date", "")),
                str(c.get("emotional_state", "")),
                str(c.get("stress_level", "")),
                str(c.get("cognitive_load", "")),
                str(c.get("motivation_level", "")),
                str(round(c.get("vader_compound") or 0.0, 2)),
                str(c.get("dominant_emotion", "")),
                str(c.get("cbt_category", "")),
            ])

        col_widths = [2.8*cm, 1.4*cm, 1.4*cm, 1.8*cm, 1.8*cm, 1.8*cm, 2.4*cm, 2.4*cm]
        t2 = Table(rows, colWidths=col_widths, repeatRows=1)
        t2.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), BLACK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 7.5),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.HexColor("#f9f9f9"), WHITE]),
            ("GRID",          (0, 0), (-1, -1), 0.4, LGRAY),
            ("LEFTPADDING",   (0, 0), (-1, -1), 5),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 5),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("ALIGN",         (1, 0), (-1, -1), "CENTER"),
        ]))
        story.append(t2)

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=LGRAY))
    story.append(Paragraph(
        "MindTrack is not a medical device. For clinical support please contact a licensed mental health professional.",
        body_style
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()
